import { 
  Activity, 
  ActivityType, 
  ChangeLogEntry, 
  ChangeType, 
  Company, 
  CompanyStatus, 
  Contact, 
  Deal, 
  DealStage, 
  FieldTrackingPolicy 
} from './types';

export const MOCK_COMPANIES: Company[] = [
  {
    id: '1',
    name: '삼성전자',
    industry: '제조/반도체',
    companyType: '대기업',
    employeeCount: 10000,
    revenueScale: '10조+',
    energyGrade: 'A',
    city: '수원',
    country: 'KR',
    createdAt: '2020-04-12',
    owner: '김지훈',
    leadSource: '파트너 추천',
    tags: ['엔터프라이즈', '핵심계정'],
    score: 92,
    repName: '김철수',
    repPosition: '구매팀 부장',
    repPhone: '010-1234-5678',
    email: 'cs.kim@samsung.com',
    status: CompanyStatus.PROPOSAL,
    lastContact: '2024-11-24',
    notes: '프리미엄 요금제 도입 검토 중. 내년 예산안 반영 요청함.'
  },
  {
    id: '2',
    name: '현대자동차',
    industry: '제조/자동차',
    companyType: '대기업',
    employeeCount: 8000,
    revenueScale: '10조+',
    energyGrade: 'B',
    city: '서울',
    country: 'KR',
    createdAt: '2021-02-10',
    owner: '오세린',
    leadSource: '컨퍼런스',
    tags: ['전략', '모빌리티'],
    score: 88,
    repName: '이영희',
    repPosition: '기술연구소 수석',
    repPhone: '010-9876-5432',
    email: 'yh.lee@hyundai.com',
    status: CompanyStatus.EVALUATION,
    lastContact: '2024-11-22',
    notes: '1차 미팅 완료. PoC 진행을 위한 기술 문서 송부 필요.'
  },
  {
    id: '3',
    name: 'LG에너지솔루션',
    industry: '배터리/에너지',
    companyType: '대기업',
    employeeCount: 6000,
    revenueScale: '5조+',
    energyGrade: 'A',
    city: '오창',
    country: 'KR',
    createdAt: '2022-06-01',
    owner: '정우석',
    leadSource: '웹 유입',
    tags: ['ESG', '고효율'],
    score: 76,
    repName: '박민수',
    repPosition: 'IT 기획 팀장',
    repPhone: '010-5555-4444',
    email: 'ms.park@lges.com',
    status: CompanyStatus.LEAD,
    lastContact: '2024-11-15',
    notes: '링크드인을 통한 콜드 메일 발송. 아직 회신 없음.'
  },
  {
    id: '4',
    name: 'SK하이닉스',
    industry: '반도체/제조',
    companyType: '대기업',
    employeeCount: 7000,
    revenueScale: '10조+',
    energyGrade: 'B',
    city: '이천',
    country: 'KR',
    createdAt: '2020-11-18',
    owner: '김지훈',
    leadSource: '기존 고객 추천',
    tags: ['메모리', '전략'],
    score: 90,
    repName: '정수진',
    repPosition: '구매 담당',
    repPhone: '010-2222-3333',
    email: 'sj.jung@sk.com',
    status: CompanyStatus.NEGOTIATION,
    lastContact: '2024-11-25',
    notes: '물량 할인율 협의 중. 11월 중 계약 체결 예상.'
  },
  {
    id: '5',
    name: '카카오',
    industry: '플랫폼/인터넷',
    companyType: '대기업',
    employeeCount: 3000,
    revenueScale: '1조+',
    energyGrade: 'A',
    city: '성남',
    country: 'KR',
    createdAt: '2021-08-03',
    owner: '오세린',
    leadSource: '세미나',
    tags: ['디지털', '핵심계정'],
    score: 95,
    repName: '최동훈',
    repPosition: '플랫폼실 이사',
    repPhone: '010-6666-7777',
    email: 'dh.choi@kakao.com',
    status: CompanyStatus.CONTRACT,
    lastContact: '2024-11-20',
    notes: '전자 계약서 발송 완료. 서명 대기 중.'
  },
  {
    id: '6',
    name: '네이버',
    industry: '플랫폼/인터넷',
    companyType: '대기업',
    employeeCount: 3500,
    revenueScale: '1조+',
    energyGrade: 'B',
    city: '성남',
    country: 'KR',
    createdAt: '2021-10-10',
    owner: '정우석',
    leadSource: '리드 광고',
    tags: ['검색', '플랫폼'],
    score: 70,
    repName: '강지영',
    repPosition: '클라우드 사업부 리더',
    repPhone: '010-9999-8888',
    email: 'jy.kang@navercorp.com',
    status: CompanyStatus.LOST,
    lastContact: '2024-09-10',
    notes: '자체 솔루션 개발로 인한 도입 취소.'
  },
  {
    id: '7',
    name: '우아한형제들',
    industry: '플랫폼/배달',
    companyType: '중견기업',
    employeeCount: 1500,
    revenueScale: '5000억+',
    energyGrade: 'A',
    city: '서울',
    country: 'KR',
    createdAt: '2022-02-14',
    owner: '김지훈',
    leadSource: '소개',
    tags: ['푸드', 'API'],
    score: 82,
    repName: '한승우',
    repPosition: '개발 팀장',
    repPhone: '010-1010-1010',
    email: 'sw.han@woowahan.com',
    status: CompanyStatus.EVALUATION,
    lastContact: '2024-11-26',
    notes: 'API 연동 관련 기술 문의. 다음 주 화상 미팅 예정.'
  }
];

export const STATUS_COLORS: Record<CompanyStatus, string> = {
  [CompanyStatus.LEAD]: 'bg-slate-100 text-slate-600',
  [CompanyStatus.EVALUATION]: 'bg-blue-50 text-blue-700',
  [CompanyStatus.PROPOSAL]: 'bg-yellow-50 text-yellow-700',
  [CompanyStatus.NEGOTIATION]: 'bg-amber-50 text-amber-800',
  [CompanyStatus.CONTRACT]: 'bg-green-50 text-green-700',
  [CompanyStatus.LOST]: 'bg-red-50 text-red-700',
};

export const STAGE_COLORS: Record<DealStage, string> = {
  [DealStage.LEAD]: 'bg-slate-100 text-slate-700',
  [DealStage.EVALUATION]: 'bg-blue-50 text-blue-700',
  [DealStage.PROPOSAL]: 'bg-indigo-50 text-indigo-700',
  [DealStage.NEGOTIATION]: 'bg-amber-50 text-amber-800',
  [DealStage.CONTRACT]: 'bg-green-50 text-green-700',
  [DealStage.LOST]: 'bg-red-50 text-red-700'
};

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'c1',
    companyId: '1',
    name: '김철수',
    title: '구매팀 부장',
    department: '구매',
    email: 'cs.kim@samsung.com',
    phone: '010-1234-5678',
    role: 'Economic Buyer',
    lastInteraction: '2024-11-22',
    type: '의사결정자'
  },
  {
    id: 'c2',
    companyId: '1',
    name: '윤다인',
    title: 'IT 기획 파트장',
    department: 'IT기획',
    email: 'dy.yoon@samsung.com',
    phone: '010-4444-2222',
    role: 'Champion',
    lastInteraction: '2024-11-24',
    type: '실무담당자'
  },
  {
    id: 'c3',
    companyId: '2',
    name: '이영희',
    title: '기술연구소 수석',
    department: 'R&D',
    email: 'yh.lee@hyundai.com',
    phone: '010-9876-5432',
    role: 'Technical Buyer',
    lastInteraction: '2024-11-22',
    type: '의사결정자'
  },
  {
    id: 'c4',
    companyId: '3',
    name: '박민수',
    title: 'IT 기획 팀장',
    department: 'IT 기획',
    email: 'ms.park@lges.com',
    phone: '010-5555-4444',
    role: 'Influencer',
    lastInteraction: '2024-11-15',
    type: '실무담당자'
  },
  {
    id: 'c5',
    companyId: '4',
    name: '정수진',
    title: '구매 담당',
    department: '구매',
    email: 'sj.jung@sk.com',
    phone: '010-2222-3333',
    role: 'Economic Buyer',
    lastInteraction: '2024-11-25',
    type: '의사결정자'
  },
  {
    id: 'c6',
    companyId: '5',
    name: '최동훈',
    title: '플랫폼실 이사',
    department: '플랫폼',
    email: 'dh.choi@kakao.com',
    phone: '010-6666-7777',
    role: 'Sponsor',
    lastInteraction: '2024-11-20',
    type: '의사결정자'
  },
  {
    id: 'c7',
    companyId: '7',
    name: '한승우',
    title: '개발 팀장',
    department: '개발',
    email: 'sw.han@woowahan.com',
    phone: '010-1010-1010',
    role: 'Champion',
    lastInteraction: '2024-11-26',
    type: '실무담당자'
  }
];

export const MOCK_DEALS: Deal[] = [
  {
    id: 'd1',
    companyId: '1',
    contactId: 'c1',
    name: '스마트 팩토리 모니터링 SaaS',
    stage: DealStage.NEGOTIATION,
    amount: 1200000000,
    expectedCloseDate: '2025-01-20',
    status: '진행',
    owner: '김지훈',
    lastUpdated: '2024-11-24'
  },
  {
    id: 'd2',
    companyId: '2',
    contactId: 'c3',
    name: '연구소 협업 플랫폼',
    stage: DealStage.PROPOSAL,
    amount: 450000000,
    expectedCloseDate: '2024-12-15',
    status: '진행',
    owner: '오세린',
    lastUpdated: '2024-11-22'
  },
  {
    id: 'd3',
    companyId: '3',
    contactId: 'c4',
    name: '에너지 사용량 최적화 PoC',
    stage: DealStage.EVALUATION,
    amount: 150000000,
    expectedCloseDate: '2025-02-10',
    status: '진행',
    owner: '정우석',
    lastUpdated: '2024-11-15'
  },
  {
    id: 'd4',
    companyId: '4',
    contactId: 'c5',
    name: '데이터 레이크 구축 프로젝트',
    stage: DealStage.CONTRACT,
    amount: 2000000000,
    expectedCloseDate: '2024-11-30',
    status: '성공',
    owner: '김지훈',
    lastUpdated: '2024-11-25'
  },
  {
    id: 'd5',
    companyId: '5',
    contactId: 'c6',
    name: '커머스 리포팅 자동화',
    stage: DealStage.CONTRACT,
    amount: 380000000,
    expectedCloseDate: '2024-11-18',
    status: '성공',
    owner: '오세린',
    lastUpdated: '2024-11-20'
  },
  {
    id: 'd6',
    companyId: '6',
    contactId: 'c5',
    name: '클라우드 전환 컨설팅',
    stage: DealStage.LOST,
    amount: 500000000,
    expectedCloseDate: '2024-09-01',
    status: '실패',
    owner: '정우석',
    lastUpdated: '2024-09-10'
  },
  {
    id: 'd7',
    companyId: '7',
    contactId: 'c7',
    name: '배달API 실시간 모니터링',
    stage: DealStage.EVALUATION,
    amount: 250000000,
    expectedCloseDate: '2025-01-05',
    status: '진행',
    owner: '김지훈',
    lastUpdated: '2024-11-26'
  }
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'a1',
    companyId: '1',
    contactId: 'c1',
    dealId: 'd1',
    type: ActivityType.MEETING,
    summary: '2차 PoC 결과 공유 및 보안 요구사항 정리',
    actor: '김지훈',
    occurredAt: '2024-11-23T09:00:00Z',
    nextStep: '수정된 견적안 재송부'
  },
  {
    id: 'a2',
    companyId: '1',
    contactId: 'c2',
    dealId: 'd1',
    type: ActivityType.EMAIL,
    summary: '에너지 등급 상향 자료 공유',
    actor: '김지훈',
    occurredAt: '2024-11-21T07:30:00Z'
  },
  {
    id: 'a3',
    companyId: '2',
    contactId: 'c3',
    dealId: 'd2',
    type: ActivityType.MEETING,
    summary: 'R&D 협업 요구사항 워크숍',
    actor: '오세린',
    occurredAt: '2024-11-22T05:00:00Z',
    nextStep: 'PoC 범위 정의서 전달'
  },
  {
    id: 'a4',
    companyId: '3',
    contactId: 'c4',
    dealId: 'd3',
    type: ActivityType.CALL,
    summary: 'PoC 일정 재조율 요청',
    actor: '정우석',
    occurredAt: '2024-11-15T02:00:00Z'
  },
  {
    id: 'a5',
    companyId: '4',
    contactId: 'c5',
    dealId: 'd4',
    type: ActivityType.VISIT,
    summary: '온사이트 보안 검증 완료',
    actor: '김지훈',
    occurredAt: '2024-11-24T08:30:00Z',
    nextStep: '계약서 최종본 송부'
  },
  {
    id: 'a6',
    companyId: '5',
    contactId: 'c6',
    dealId: 'd5',
    type: ActivityType.EMAIL,
    summary: '전자계약서 서명 리마인드 발송',
    actor: '오세린',
    occurredAt: '2024-11-20T03:30:00Z'
  },
  {
    id: 'a7',
    companyId: '7',
    contactId: 'c7',
    dealId: 'd7',
    type: ActivityType.MEETING,
    summary: 'API 연동 구조 리뷰 및 SLA 합의',
    actor: '김지훈',
    occurredAt: '2024-11-26T04:00:00Z',
    nextStep: '성능 테스트 계획 공유'
  }
];

export const MOCK_CHANGE_LOGS: ChangeLogEntry[] = [
  {
    id: 'chg1',
    entityType: 'Company',
    entityId: '1',
    fieldName: '에너지 등급',
    oldValue: 'B',
    newValue: 'A',
    changedBy: '김지훈',
    changedAt: '2024-11-12T09:00:00Z',
    changeType: ChangeType.UPDATE,
    reason: '현장 감사 결과 상향',
    tracked: true,
    latencyMinutes: 45
  },
  {
    id: 'chg2',
    entityType: 'Deal',
    entityId: 'd1',
    fieldName: '단계',
    oldValue: DealStage.PROPOSAL,
    newValue: DealStage.NEGOTIATION,
    changedBy: '김지훈',
    changedAt: '2024-11-24T11:00:00Z',
    changeType: ChangeType.APPROVAL,
    reason: '할인율 승인 완료',
    tracked: true,
    latencyMinutes: 20
  },
  {
    id: 'chg3',
    entityType: 'Deal',
    entityId: 'd4',
    fieldName: '계약 금액',
    oldValue: '1,800,000,000',
    newValue: '2,000,000,000',
    changedBy: '김지훈',
    changedAt: '2024-11-25T06:00:00Z',
    changeType: ChangeType.UPDATE,
    reason: '추가 모듈 포함',
    tracked: true,
    latencyMinutes: 30
  },
  {
    id: 'chg4',
    entityType: 'Company',
    entityId: '6',
    fieldName: '상태',
    oldValue: CompanyStatus.NEGOTIATION,
    newValue: CompanyStatus.LOST,
    changedBy: '정우석',
    changedAt: '2024-09-10T01:00:00Z',
    changeType: ChangeType.UPDATE,
    reason: '고객 내부 빌드 결정',
    tracked: true,
    latencyMinutes: 120
  },
  {
    id: 'chg5',
    entityType: 'Contact',
    entityId: 'c7',
    fieldName: '전화번호',
    oldValue: '010-0000-0000',
    newValue: '010-1010-1010',
    changedBy: '김지훈',
    changedAt: '2024-11-26T04:10:00Z',
    changeType: ChangeType.UPDATE,
    reason: '연락처 정정',
    tracked: false,
    latencyMinutes: 240
  },
  {
    id: 'chg6',
    entityType: 'Company',
    entityId: '3',
    fieldName: '메모',
    oldValue: '...긴 메모 내용의 일부 (255자 스니펫)...',
    newValue: '...업데이트된 긴 메모 내용의 일부 (255자 스니펫)...',
    oldValueLength: 320,
    newValueLength: 540,
    oldValueTruncated: true,
    newValueTruncated: true,
    changedBy: '정우석',
    changedAt: '2024-11-16T01:20:00Z',
    changeType: ChangeType.UPDATE,
    reason: '장문의 회의 기록 업데이트',
    tracked: true,
    latencyMinutes: 60,
    retentionUntil: '2025-11-16T01:20:00Z',
    policyId: 'policy-3'
  }
];

export const MOCK_FIELD_TRACKING_POLICIES: FieldTrackingPolicy[] = [
  {
    id: 'policy-1',
    entityType: 'Company',
    fieldName: '에너지 등급',
    isTracked: true,
    retentionDays: 365,
    maxLength: 255,
    excludeLongText: true
  },
  {
    id: 'policy-2',
    entityType: 'Deal',
    fieldName: '단계',
    isTracked: true,
    retentionDays: 365,
    maxLength: 255,
    excludeLongText: true
  },
  {
    id: 'policy-3',
    entityType: 'Company',
    fieldName: '메모',
    isTracked: false,
    retentionDays: 90,
    maxLength: 255,
    excludeLongText: true
  }
];
